package com.zrosen10.fitnessTracker.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

import java.util.Date;

import com.zrosen10.fitnessTracker.dto.GoalDTO;

/**
 * Entity class representing a fitness goal in the system.
 * This class is mapped to the database table using JPA annotations.
 * The @Data annotation from Lombok automatically generates getters, setters,
 * equals, hashCode, and toString methods.
 */
@Entity
@Data
public class Goal {

    /**
     * Unique identifier for the goal.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Textual description of the goal (e.g., "Run 5 miles", "Lose 10 pounds").
     */
    private String description;

    /**
     * Date when the goal was set or should begin.
     */
    private Date startDate;

    /**
     * Target date by which the goal should be accomplished.
     */
    private Date endDate;

    /**
     * Flag indicating whether the goal has been achieved.
     */
    private boolean achieved;

    /**
     * Converts this entity to a Data Transfer Object (DTO).
     * This method helps separate the internal entity structure from the external
     * API representation.
     * 
     * @return A GoalDTO containing the same data as this entity
     */
    public GoalDTO getGoalDTO() {

        // Create a new DTO instance
        GoalDTO goalDTO = new GoalDTO();

        // Copy all properties from entity to DTO
        goalDTO.setId(id);
        goalDTO.setDescription(description);
        goalDTO.setStartDate(startDate);
        goalDTO.setEndDate(endDate);
        goalDTO.setAchieved(achieved);

        return goalDTO;
    }
}